### ISSUE TITLE
asynquence-contrib version Issue

### ISSUE THREAD

**Issue by neolok** [getify/You-Dont-Know-JS#480] opened 2015-07-06 02:25 UTC
Was following your instructions : Real-Time Web with Node.js @ FrontEnd Masters
when attempting to npm install asynquence and asynquence-contrib.. got following error
*************************************************
61 error node v0.12.6
62 error npm  v2.11.2
63 error code TARGET
64 error notarget No compatible version found: asynquence-contrib@'*'
64 error notarget Valid install targets:
64 error notarget ["0.1.0-a","0.1.1-a","0.1.2-a","0.1.3-a","0.1.4-a","0.1.5-a","0.1.6-a","0.1.6-b","0.1.7-a","0.1.7-b","0.1.8-a","0.1.8-b","0.1.9-a","0.1.10-a","0.1.10-b","0.1.10-c","0.1.10-d","0.1.10-e","0.1.10-f","0.1.10-g","0.1.10-h","0.1.10-i","0.1.10-j","0.1.10-k","0.1.10-l","0.1.10-m","0.1.11-a","0.2.0-a","0.2.1-a","0.2.2-a","0.2.2-b","0.2.3-a","0.3.0-a","0.3.0-b","0.3.0-c","0.3.1-c","0.4.0-a","0.5.0-a","0.5.0-b","0.5.1-a","0.5.2-a","0.5.2-b","0.5.2-c","0.6.0-a","0.6.1-a","0.6.2-a","0.7.0-a","0.7.0-b","0.7.0-c","0.7.1-a","0.8.0-a","0.9.0-a","0.9.1-a"]
64 error notarget
64 error notarget This is most likely not a problem with npm itself.
64 error notarget In most cases you or one of your dependencies are requesting
64 error notarget a package version that doesn't exist.
65 verbose exit [ 1, true ]
***************************************************************
My Node version: V0.12.6

**Comment by getify** [comment] 2015-07-06 04:04
what is your npm version?

```
npm --version
```

**Comment by neolok** [comment] 2015-07-06 04:08
npm v2.11.2


On Jul 6, 2015, at 12:05 AM, Kyle Simpson <notifications@github.com> wrote:

what is your npm version?

npm --version

**Comment by getify** [comment] 2015-07-06 04:55
This works fine for me on npm@2.11.0. So... looks like it's some kind of breaking change introduced to npm after 2.11.0. Confirmed with someone else that it happens in 2.12.0 as well.

**Comment by getify** [comment] 2015-07-09 14:17
Tracking elsewhere, so closing this.

**Closed by getify** 2015-07-09 14:17 UTC
