### ISSUE TITLE
Scope & Closures - Chapter 3 - Try Catch scope

### ISSUE THREAD

**Issue by massimocode** [getify/You-Dont-Know-JS#640] opened 2016-01-20 09:53 UTC
Hi

Thanks for all the hard work on this series, it really is fantastic!

I read about the try/catch's block scope in this chapter and the sentence "It's a very little known fact that JavaScript in ES3 specified the **variable declaration** in the catch clause of a try/catch to be block-scoped to the catch block."

This led me to believe that there was implicit block scoping inside the catch clause so I tried this and it didn't work how I expected:
```
var arrayToReturn = [];
var i;
for (i = 1; i <= finalNumber; i++) {
    try {
        undefined();
    } catch (e) {
        var m = i;
        arrayToReturn.push(function () {
            return m;
        });
    }
}
return arrayToReturn;
```
The returned array is supposed to contain functions that return 1, 2, 3, 4... respectively. However, all of them return the finalNumber.

I was thinking about a slight amendment to more explicitly say "It's a very little known fact that JavaScript in ES3 specified the **error variable** in the catch clause of a try/catch to be block-scoped to the catch block."

Any thoughts?

**Comment by getify** [comment] 2016-01-20 15:11
My intention with the wording should be read as inflected as: "...specified **the** variable declaration in the catch clause..." So, "the" instead of "a" was intended to indicate that it's the specific and singular declaration created by the `catch` clause.

Also, you should be aware: all blocks in JS (as of ES6) can be "block scoped", but it's never the `var` that does it. You have to use `let`. So, you *could* put a `let` inside a `catch` block and it would absolutely *also* be block scoped there. In that way, you can sorta think of `catch` like this:

```js
try { .. }
catch (let err) {
  ..
}
```

**Comment by getify** [comment] 2016-02-13 15:01
Closing for now, reopen if more clarification needed.

**Closed by getify** 2016-02-13 15:01 UTC
