### ISSUE TITLE
Hoisting

### ISSUE THREAD

**Issue by mohanr** [getify/You-Dont-Know-JS#403] opened 2015-04-01 07:39 UTC
I think it is called hoisting.  When a for loop repeatedly accesses the length property of an array the VM may cache it. Does the VM hoist the length property and cache if it knows the loop is iterating a certain number of times ? How do we check with a profiler ?

**Comment by getify** [comment] 2015-04-04 12:23
That usage of "hoisting" is something I've heard from compiler/engine folks, but it's not really the same thing as how most people in/around the JS community mean "hositing" (variable scoping).

**Comment by mohanr** [comment] 2015-04-05 02:16
Ok. I was trying to avoid the same mistakes I made when I used Java. Not understanding how the VM and GC work. We were asked to cache the length of the array but the VM could be doing this and many other things already. Is there a list of such things the VM does for us ?

**Comment by getify** [comment] 2015-04-05 17:34
Each VM is quite different. But yes, in general, the VM's are pretty smart, and the tricks you might do to "help" it are generally unnecessary (and sometimes harmful to the cause). You might read [Chapter 6, *Benchmarking & Tuning*](https://github.com/getify/You-Dont-Know-JS/blob/master/async%20&%20performance/ch6.md#chapter-6-benchmarking--tuning) of *Async & Performance* for more about sanity checking how you approach performance optimization of your code.

**Comment by getify** [comment] 2015-04-23 15:16
closing for now. reopen if there's more to answer.

**Closed by getify** 2015-04-23 15:16 UTC
Labels: question
